/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.21
 * Generated at: 2017-04-06 00:49:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar", Long.valueOf(1491437105481L));
    _jspx_dependants.put("jar:file:/C:/Users/Alice/Source/Repos/moneyControl/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/MoneyControl/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar!/META-INF/c.tld", Long.valueOf(1323265578000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Money Control</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.css\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".font-h2{\r\n");
      out.write("\tfont-family: Times New Roman;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-signin {\r\n");
      out.write("\tmax-width: 450px;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".centro-vertical {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 50%;\r\n");
      out.write("\tleft:50%;\r\n");
      out.write("\ttransform: translate(-50%,-50%);\r\n");
      out.write("\tfont-family: inherit;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button {\r\n");
      out.write("  color: #ccc;\r\n");
      out.write("  background-color: #242424;\r\n");
      out.write("  border-color: #242424;\r\n");
      out.write("}\r\n");
      out.write(".button:focus,\r\n");
      out.write(".button.focus {\r\n");
      out.write("  color: #ccc;\r\n");
      out.write("  background-color: #7f7f7f;\r\n");
      out.write("  border-color: #8c8c8c;\r\n");
      out.write("}\r\n");
      out.write(".button:hover {\r\n");
      out.write("  color: #ccc;\r\n");
      out.write("  background-color: #7f7f7f;\r\n");
      out.write("  border-color: #adadad;\r\n");
      out.write("}\r\n");
      out.write(".button:active,\r\n");
      out.write(".button.active,\r\n");
      out.write(".open > .dropdown-toggle.button {\r\n");
      out.write("  color: #ccc;\r\n");
      out.write("  background-color: #7f7f7f;\r\n");
      out.write("  border-color: #adadad;\r\n");
      out.write("}\r\n");
      out.write(".button:active:hover,\r\n");
      out.write(".button.active:hover,\r\n");
      out.write(".open > .dropdown-toggle.button:hover,\r\n");
      out.write(".button:active:focus,\r\n");
      out.write(".button.active:focus,\r\n");
      out.write(".open > .dropdown-toggle.button:focus,\r\n");
      out.write(".button:active.focus,\r\n");
      out.write(".button.active.focus,\r\n");
      out.write(".open > .dropdown-toggle.button.focus {\r\n");
      out.write("  color: #ccc;\r\n");
      out.write("  background-color: #d4d4d4;\r\n");
      out.write("  border-color: #8c8c8c;\r\n");
      out.write("}\r\n");
      out.write(".button:active,\r\n");
      out.write(".button.active,\r\n");
      out.write(".open > .dropdown-toggle.button {\r\n");
      out.write("  background-image: none;\r\n");
      out.write("}\r\n");
      out.write(".button.disabled,\r\n");
      out.write(".button[disabled],\r\n");
      out.write("fieldset[disabled] .button,\r\n");
      out.write(".button.disabled:hover,\r\n");
      out.write(".button[disabled]:hover,\r\n");
      out.write("fieldset[disabled] .button:hover,\r\n");
      out.write(".button.disabled:focus,\r\n");
      out.write(".button[disabled]:focus,\r\n");
      out.write("fieldset[disabled] .button:focus,\r\n");
      out.write(".button.disabled.focus,\r\n");
      out.write(".button[disabled].focus,\r\n");
      out.write("fieldset[disabled] .button.focus,\r\n");
      out.write(".button.disabled:active,\r\n");
      out.write(".button[disabled]:active,\r\n");
      out.write("fieldset[disabled] .button:active,\r\n");
      out.write(".button.disabled.active,\r\n");
      out.write(".button[disabled].active,\r\n");
      out.write("fieldset[disabled] .button.active {\r\n");
      out.write("  background-color: #242424;\r\n");
      out.write("  border-color: #242424;\r\n");
      out.write("}\r\n");
      out.write(".button .badge {\r\n");
      out.write("  color: #242424;\r\n");
      out.write("  background-color: #ccc;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<form class=\"form-signin centro-vertical\" action=\"loginServlet\" method=\"post\">\r\n");
      out.write("\t\t\t<h2 class=\"form-signin-heading font-h2\" align=\"center\">\r\n");
      out.write("\t\t\t\tMoney Control <span class=\"glyphicon glyphicon-piggy-bank\"></span>\r\n");
      out.write("\t\t\t</h2>\r\n");
      out.write("\t\t\t<label for=\"inputUserName\" class=\"sr-only\"></label> <br> <input\r\n");
      out.write("\t\t\t\ttype=\"email\" id=\"inputUserName\" class=\"form-control input-lg\"\r\n");
      out.write("\t\t\t\tplaceholder=\"Email\" name=\"email\" required>\r\n");
      out.write("\t\t\t<label for=\"inputPassword\" class=\"sr-only\"></label> <br> <input\r\n");
      out.write("\t\t\t\ttype=\"password\" id=\"inputPassword\" class=\"form-control input-lg\"\r\n");
      out.write("\t\t\t\tplaceholder=\"Senha\" name=\"password\" required> <br>\r\n");
      out.write("\t\t\t<button class=\"btn btn-lg btn-success btn-block button\" type=\"submit\">Entrar</button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->\r\n");
      out.write("    <script src=\"js/jquery-1.11.3.js\"></script>\r\n");
      out.write("    <!-- Include all compiled plugins (below), or include individual files as needed -->\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<br>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /login.jsp(116,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loggedin == false }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t<div class=\"alert alert-danger alert-dismissible\" role=\"alert\">\r\n");
        out.write("\t\t\t\t<span class=\"glyphicon glyphicon-alert\"></span>\r\n");
        out.write("\t\t\t\t\t<b>Email ou senha incorreto(s).</b>\r\n");
        out.write("\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>\r\n");
        out.write("\t\t\t</div>\r\n");
        out.write("\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }
}
